<div class="notifyer">
    <div class="ui positive message" id="success_message">
        <i class="close icon"></i>
        <div class="header" id="title"></div>
        <p id="message"></p>
        <div class="ui divider"></div>
        <p id="footer">
            <a class="positive ui button" data-href="<?=$mvc->url('/install.php', [
				'product' => $product,
				'step' => $query_step+1,
			])?>" id="save-next" style="cursor: pointer" role="button">Продолжить</a>
        </p>
    </div>

    <div class="ui negative message" id="error_message">
        <i class="close icon"></i>
        <div class="header" id="title"></div>
        <p id="message"></p>
        <div class="ui divider"></div>
        <p id="footer"></p>
    </div>
</div>

<div class="ui steps">
    <div class="step">
        <i class="truck icon"></i>
        <div class="content">
            <div class="title">Доставка</div>
            <div class="description">Выберите тип доставки</div>
        </div>
    </div>
    <div class="active step">
        <i class="payment icon"></i>
        <div class="content">
            <div class="title">Оплата</div>
            <div class="description">Способ оплаты</div>
        </div>
    </div>
    <div class="disabled step">
        <i class="info icon"></i>
        <div class="content">
            <div class="title">Подтвердить заказ</div>
        </div>
    </div>
</div>

<div class="ui segment install_interface">
	<div class="content">
        <h2 class="ui header">
            <i class="settings icon"></i>
            <small class="content"><?=$view->getTitle()?> <div class="sub header"><?=$step?></div></small>
        </h2>

        <div class="text">
			<p><?=$description?></p>

			<?php switch (true) {
                case $is_main: ?>
                    <form role="form" method="get" action="<?=$mvc->url('/install.php')?>">
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <label for="select-product" style="line-height: 40px">Продукт:</label>
                                <select class="custom-select" name="product" id="select-product" style="float: right; height: 40px">
                                    <option selected>Выбирите тип продукта</option>
                                    <option value="module">Модуль</option>
                                </select>
                            </div>

                            <div class="form-group col-md-4">
                                <label class="custom-file">
                                    <input type="file" id="file2" class="custom-file-input" accept="application/json">
                                    <span class="custom-file-control" data-file="Выбирите файл..."></span>
                                </label>
                            </div>

                            <div class="form-group col-md-3">
                                <button type="submit" class="btn btn-primary btn-block">Установить</button>
                            </div>
                        </div>
                    </form>
                    <?php break;

                case $table:
                    $view->renderValidationTable($table); ?>

                    <script type="application/javascript">
                        $(document).ready(function () {
                            var element_sum = $('#server_validation_result > tr[data-active="disabled"]').length;

                            if (element_sum > 0) {
                                $('#next-button').addClass('disabled');
                            } else {
                                $('#next-button').removeClass('disabled');
                            }

                            $('#next-button').click(function () {
                                $.cookie("step2", 'true', { path: '/install.sass.php', expires: 2});

                                var href = $(this).data('href');

                                document.location.href = href;
                            });
                        });
                    </script>
                    <?php break;
                case $form: ($form)?$view->insert($form,'.phtml'):null; break;

                default: break;
            } ?>

            <p style="margin-top: 15px; margin-bottom: 0;">
                <button type="button" class="ui button"  onclick="document.location.reload()">Обновить</button>
                <a href="#" onclick="return false" data-href="<?=$mvc->url( '/install.php', [
				'product' => $product,
				'step' => $query_step+1,
				])?>" id="next-button" class="ui primary disabled button" role="button" style="float: right;">Продолжить</a>
            </p>
		</div>
	</div>
</div>

<script type="application/javascript">
	$(document).ready(function () {
		$('input[type=file]').on('change', function(){
			var filename = $(this).val().split('\\');
			filename = filename[filename.length - 1];

			$('.custom-file-control').attr('data-file', filename);
		});
	});
</script>
