<!DOCTYPE html>
<html xml:lang="ru" lang="ru">
	<head>
		<title><?php echo $this->getTitle(); ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

		<!-- head::icon -->
		<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
		<link href="/favicon.ico" rel="icon" type="image/x-icon" />

		<!-- head::css -->
		<link rel="stylesheet" href="<?=$this->basePath('css/install.css')?>" />
		<link rel="stylesheet" href="<?=$this->semanticPath('semantic.min.css')?>" />

        <!-- head::js -->
		<script type="text/javascript" src="<?=$this->pluginsPath('jquery.min.js')?>"></script>
        <script type="text/javascript" src="<?=$this->pluginsPath('jquery.cookie.js')?>"></script>
		<script type="text/javascript" src="<?=$this->semanticPath('semantic.min.js')?>"></script>

    </head>
	<body class="grid">

		<div class="ui container">
            <?php echo $content; ?>
		</div>

		<footer class="ui sticky fixed bottom">
			<div class="ui container">
				<p>CMS Cilaster • 2017 • by <span class="text-uppercase">JM Organization</span></p>
			</div>
		</footer>

	</body>
</html>