<?php
	$mvc = new \Cilaster\API\Http\Mvc();
	$view = new \Cilaster\MVC\Application\ApplicationView();

?>

<table class="table table-sm">
	<thead class="thead-default">
	<tr>
		<th>#</th>
		<th>Требование</th>
		<th class="text-right">Статус</th>
		<th>Значение</th>
	</tr>
	</thead>
	<tbody id="server-validation-result">
	<?php $iteration_id = 0;
	foreach ($table as $key => $value) {
		$iteration_id++?>
		<tr class="<?php if ($value || $value == 1){?>active<?php } else {?>disabled<?php } ?>">
			<th scope="row"><?=$iteration_id?></th>
			<td class="border border-right-0 border-bottom-0"><?=$key?></td>
			<td class="border border-left-0 border-bottom-0 text-right">
				<?=($value || $value == 1)?'<b class="text-success">Да</b>':'<b class="text-danger">Нет</b>'?>
			</td>
			<td><?=($value != 1)?$value:null?></td>
		</tr>
	<?php } ?>
	</tbody>
</table>
