<form method="post">
    <div class="form-row">
        <div class="form-group col-md-8" id="host-row">
            <label for="host">Host</label>
            <input required type="text" class="form-control form-control-sm text-right" name="host" id="host" placeholder="Введите host вашей базы данных...">
            <small id="host-help" class="form-text text-muted">В качестве Host стоит указать имя сервера, к примеру <i>example.com</i></small>
        </div>

        <div class="form-group col-md-4">
            <label for="port">Port</label>
            <input required type="text" minlength="2" maxlength="6" class="form-control form-control-sm" name="port" id="port" placeholder="Введите port вашей Базы Данных...">
            <small id="port-help" class="form-text text-muted">Обычно, это число из 4 цыфр - 3306</small>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="database">Имя базы данных</label>
            <input required type="text" class="form-control form-control-sm" name="database" id="database" placeholder="Введите название вашей базы данных...">
        </div>

        <div class="form-group col-md-4">
            <label for="driver">Тип базы данных</label>
            <select required class="form-control form-control-sm custom-select" name="driver" id="driver">
                <option selected disabled>Выбирите тип базы данных</option>
                <option value="pdo_mysql">MySQL (PDO) [recommended]</option>
                <option value="mysqli">MySQL</option>
            </select>
        </div>

        <div class="form-group col-md-2">
            <label for="charset">Кодировка</label>
            <select required class="form-control form-control-sm custom-select" name="charset" id="charset">
                <option selected disabled>Выбирите кодировку</option>
                <option value="utf8">UTF-8</option>
            </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="user">Имя пользователя</label>
            <input required type="text" class="form-control form-control-sm" name="user" id="user" placeholder="Ввдите имя пользователя для доступа к базе...">
        </div>

        <div class="form-group col-md-6">
            <label for="password">Пароль</label>
            <input type="text" class="form-control form-control-sm" name="password" id="password" placeholder="Введите пароль к базе данных...">
        </div>
    </div>

    <button type="button" class="btn btn-primary btn-block" id="valid-next">Проверить соединение</button>
</form>

<script type="application/javascript">
    $('#valid-next').click(function () {
        var options = $('form').serialize().replace(/&/g,",").replace(/=/g,":");
        $('.alert').animate({ top: '-150px' }, 300);

        $.ajax({
            url: '/rest.php',
            type: 'get',
            data: { testConnection: options },
            dataType: 'json',
            success: function (data) {
                //var type_alert = (data.code === 1)?'.alert-success':((data.code === 2)?'.alert-warning':'');
                switch (data.code) {
                    case 0: break;
                    case 1: break;
                    case 2: break;
                    case 3: break;
                    default: type_alert =  break;
                }


                $(type_alert+' .status').html(data.status);
                $(type_alert+' .message').html(data.message);

                $(type_alert).animate({ top: '-30px' }, 1000);
            }
        });
    });

    $('#save-next').click(function () {
        var data_for_save = $('form').serialize();

        $.ajax({
            url: document.location.href,
            type: 'post',
            data: data_for_save,
            dataType: 'json'
        });

        $.cookie("step3", 'true', { path: '/install.php', expires: 2});

        document.location.href = $('#save-next').data('href');
    });
</script>